service: cart-service

frameworkVersion: '3'
	
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev
  environment:
    PORT: ${env:PORT}
    

functions:
  main:
    handler: dist/main.handler   	
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true